export const ENQUIRY_STATUSES = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  IN_PROGRESS: 'IN_PROGRESS',
  QUOTED: 'QUOTED',
  CONVERTED: 'CONVERTED',
  CLOSED: 'CLOSED'
};

export const CONTACT_STATUSES = {
  NEW: 'NEW',
  READ: 'READ',
  REPLIED: 'REPLIED',
  ARCHIVED: 'ARCHIVED'
};

export const GALLERY_CATEGORIES = {
  PRODUCTS: 'PRODUCTS',
  MANUFACTURING: 'MANUFACTURING',
  FACILITIES: 'FACILITIES',
  EVENTS: 'EVENTS',
  MEETINGS: 'MEETINGS',
  COMMUNITY: 'COMMUNITY',
  CORPORATE: 'CORPORATE'
};

export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  EDITOR: 'EDITOR'
};